services:
  - type: web
    name: suno-toolkit
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
